repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: "(migrations)"
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        exclude: "(migrations)"
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: "(migrations)"
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: "(migrations)"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "types-PyYAML"]
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        exclude: "(test_*)|(settings.py)|(manage.py)|(migrations)"
