repos:

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle
        exclude: 'migrations/*'

-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
    -   id: isort

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
